spring:
    profiles: 
        active: 
        - dev
        
---
#注册中心占有7001
server: 
    port: 7001        
    
spring:
    profiles: dev
    application: 
        name: mircoservice-config-eureka-client
        
eureka:
    instance: 
        hostname: eureka7001.com
    client: 
        register-with-eureka: false #当前eureka自己不注册进服务列表中
        fetch-registry: false #不通过eureka获取注册信息
        service-url: 
            defaultZone: http://eureka7001.com:7001/eureka/
            
---
server: 
    port: 7001

spring: 
    profiles: test
    application: 
        name: mircoservice-config-eureka-client
        
eureka:
    instance: 
        hostname: eureka7001.com
    client: 
        register-with-eureka: false #当前eureka自己不注册进服务列表中
        fetch-registry: false #不通过eureka获取注册信息
        service-url: 
            defaultZone: http://eureka7001.com:7001/eureka/        